openapi: 3.0.0
info:
  title: Create yor CV
  description: This is the description of the endpoints you need to use for fetching and posting data
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server

paths:
  /countries:
    get:
      summary: Returns a list of countries.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "../swagger/examples/countries.yaml#/components/schemas"

  /cities:
    get:
      summary: Returns a list of cities in Georgia.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "../swagger/examples/cities.yaml#/components/schemas"

  /degrees:
    get:
      summary: Returns a list of degrees.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "../swagger/examples/degrees.yaml#/components/schemas"

  /cvs:
    post:
      summary: Stores data.
      requestBody:
        description: Create a new contact organization
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: 6d527477c2e405a686d8426964940876
                name:
                  type: string
                  example: დავით
                surname:
                  type: string
                  example: ონიანი
                email:
                  type: email
                  example: davitoniani@redberry.ge
                phone_number:
                  type: string
                  example: 995598123456
                country_id:
                  type: integer
                  example: 80
                city:
                  type: string
                  example: Tbilisi
                experiences:
                  type: array
                  items:
                    type: object
                    properties:
                      position:
                        type: string
                        example: back-end developer
                      employer:
                        type: string
                        example: Redberry
                      start_date:
                        type: date
                        example: 2019/09/09
                      due_date:
                        type: date
                        example: 2020/09/23
                      description:
                        type: text
                        example: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ornare nunc dui, a pellentesque magna blandit dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum mattis diam nisi, at venenatis dolor aliquet vel. Pellentesque aliquet leo nec tortor pharetra, ac consectetur orci bibendum.
                educations:
                  type: array
                  items:
                    type: object
                    properties:
                      institute:
                        type: string
                        example: თსუ
                      degree_id:
                        type: integer
                        example: 13
                      due_date:
                        type: date
                        example: 2017/06/25
                      description:
                        type: text
                        example: სამართლის ფაკულტეტის მიზანი იყო მიგვეღო ფართო თეორიული ცოდნა სამართლის არსის, სისტემის, ძირითადი პრინციპების, სამართლებრივი სისტემების, ქართული სამართლის ისტორიული წყაროების, კერძო, სისხლის და საჯარო სამართლის სფეროების ძირითადი თეორიების, პრინციპებისა და რეგულირების თავისებურებების შესახებ.
                image:
                  type: file
                  format: binary
                  example: image-name.png
                about_me:
                  type: text
                  example: ეს არის აღწერა ჩემს შესახებ
                skills:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                        example: PHP
                english_lang:
                  type: integer
                  example: 4
                georgian_lang:
                  type: integer
                  example: 5
                marital_status:
                  type: string
                  example: დასაოჯახებელი
                birth_date:
                  type: date
                  example: 1995/09/18
              required:
                - token
                - name
                - surname
                - email
                - phone_number
                - country_id
                - city
                - experiences
                - educations
                - image
                - skills
                - english_lang
                - georgian_lang

          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: 6d527477c2e405a686d8426964940876
                name:
                  type: string
                  example: დავით
                surname:
                  type: string
                  example: ონიანი
                email:
                  type: email
                  example: davitoniani@redberry.ge
                phone_number:
                  type: string
                  example: 995598123456
                country_id:
                  type: integer
                  example: 80
                city:
                  type: string
                  example: Tbilisi
                experiences:
                  type: array
                  items:
                    type: object
                    properties:
                      position:
                        type: string
                        example: back-end developer
                      employer:
                        type: string
                        example: Redberry
                      start_date:
                        type: date
                        example: 2019/09/09
                      due_date:
                        type: date
                        example: 2020/09/23
                      description:
                        type: text
                        example: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ornare nunc dui, a pellentesque magna blandit dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum mattis diam nisi, at venenatis dolor aliquet vel. Pellentesque aliquet leo nec tortor pharetra, ac consectetur orci bibendum.
                educations:
                  type: array
                  items:
                    type: object
                    properties:
                      institute:
                        type: string
                        example: თსუ
                      degree_id:
                        type: integer
                        example: 13
                      due_date:
                        type: date
                        example: 2017/06/25
                      description:
                        type: text
                        example: სამართლის ფაკულტეტის მიზანი იყო მიგვეღო ფართო თეორიული ცოდნა სამართლის არსის, სისტემის, ძირითადი პრინციპების, სამართლებრივი სისტემების, ქართული სამართლის ისტორიული წყაროების, კერძო, სისხლის და საჯარო სამართლის სფეროების ძირითადი თეორიების, პრინციპებისა და რეგულირების თავისებურებების შესახებ.
                image:
                  type: file
                  format: binary
                  example: image-name.png
                about_me:
                  type: text
                  example: ეს არის აღწერა ჩემს შესახებ
                skills:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                        example: PHP
                english_lang:
                  type: integer
                  example: 4
                georgian_lang:
                  type: integer
                  example: 5
                marital_status:
                  type: string
                  example: დასაოჯახებელი
                birth_date:
                  type: date
                  example: 1995/09/18
              required:
                - token
                - name
                - surname
                - email
                - phone_number
                - country_id
                - city
                - experiences
                - educations
                - image
                - skills
                - english_lang
                - georgian_lang
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "../swagger/examples/cv.yaml#/components/schemas"

    get:
      summary: Returns a list of degrees.
      parameters:
        - name: "token"
          in: "query"
          description: "unique token chosen for your user"
          required: true
          type: "string"
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /cv/{id}:
    get:
      summary: Returns a list of degrees.
      parameters:
        - name: "id"
          in: "query"
          description: "id of the cv"
          required: true
          type: "string"
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "../swagger/examples/cv.yaml#/components/schemas"
